[package]
name = "powers"
version = "0.1.0"
edition = "2021"

[dependencies]
highs = "1.7.0"
highs-sys = "1.6.4"
rand = "0.9.0"
rand_distr = "0.5.1"
rand_xoshiro = "0.7.0"

[profile.release]
debug = 1
