on:
  push:
    tags:
      - "**[0-9]+.[0-9]+.[0-9]+*"

name: Publish

jobs:
  build_and_test_linux:
    name: Build and Test (Linux)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --all-features

  build_and_test_windows:
    name: Build and Test (Windows)
    runs-on: windows-latest
    steps:
      - name: Prepare symlink configuration
        run: git config --global core.symlinks true
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --all-features
